---
- hosts: slaves
  sudo: yes
  vars:
    monitor_host: coreos
  tasks:
#  - name: Copy hosts
#    copy: src=/etc/hosts dest=/etc/hosts
#  - name: Copy Hadoop log4j
#    template: src=log4j_hadoop.properties.j2 dest=/home/ubuntu/hadoop/etc/hadoop/log4j.properties
#  - name: Copy Hadoop hadoop-env.sh
#    copy: src=hadoop-env.sh dest=/home/ubuntu/hadoop/etc/hadoop/hadoop-env.sh
  - name: Copy Spark log4j
    template: src=log4j_spark.properties.j2 dest=/home/ubuntu/spark/conf/log4j.properties
#  - name: Copy Spark spark-defaults.conf
#    copy: src=spark-defaults.conf dest=/home/ubuntu/spark/conf/spark-defaults.conf
#  - name: Copy Spark metrics.properties
#    template: src=metrics.properties.j2 dest=/home/ubuntu/spark/conf/metrics.properties
#  - name: Craete History Server Folder
#    file: path=/home/ubuntu/spark/logs/event state=directory mode=0755
