elasticsearch:
  image: elasticsearch:5
  container_name: elasticsearch
  restart: unless-stopped
  environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - /srv/elasticsearch:/usr/share/elasticsearch/data
#  ports:
#    - "9200:9200"
logstash_shipper:
  build: ./logstash_shipper 
  restart: unless-stopped 
  command: logstash -f /etc/logstash/conf.d/logstash.conf 
# command: logstash  --debug  -f /etc/logstash/conf.d/logstash.conf 
  volumes:
    - ./logstash_shipper/config:/etc/logstash/conf.d
    - ./logstash_shipper/jmx:/etc/logstash/jmx
  ports:
    - "5044:5044"
    - "4712:4712"
    - "4713:4713"
    - "4715:4715"
  external_links:
    - sensu_rabbitmq_1
logstash_indexer:
  build: ./logstash_indexer
  restart: unless-stopped
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash_indexer/config:/etc/logstash/conf.d
  links:
    - elasticsearch
  external_links:
    - sensu_rabbitmq_1
    - sensu_influxdb_1
kibana:
  image: kibana:5
  restart: unless-stopped  
  ports:
    - "5601:5601"
  links:
    - elasticsearch
