clientt:
  image: guimaluf/sensu3
  restart: unless-stopped
  command: client
  hostname: slave9
  volumes:
   - /dev:/host_dev/:ro
   - /proc:/host_proc/:ro
   - /sys:/host_sys/:ro
   - ./conf.d:/etc/sensu/conf.d
  environment:
    CLIENT_NAME:  slave9
    CLIENT_ADDRESS: 10.82.76.12
    CLIENT_SUBSCRIPTIONS: all,default
    RABBITMQ_HOST: 200.131.6.6
    RABBITMQ_PORT: 5672
    HOST_DEV_DIR: /host_dev
    HOST_PROC_DIR: /host_proc
    HOST_SYS_DIR: /host_sys
    RUNTIME_INSTALL: snmp
