beaver:
  image: vini/beaver
#  restart: unless-stopped
  command: bash -c "sh start.sh"
  volumes:
    - ./conf/beaver.conf:/app/beaver.conf
    - /home/ubuntu/spark/logs/:/app/log
    - ./start.sh:/start.sh
#  environment:
#  -  BEAVER_OPTS: "-t rabbitmq"
