jmxtrans:
  image: fvigotti/docker-jmxtrans
  volumes:
    - ./conf/:/var/lib/jmxtrans/
  environment:
    JMXTRANS_GRAPHITE_HOST: 200.131.6.6
    JMXTRANS_GRAPHITE_PORT: 2003
    JMXTRANS_JMX_HOST: 200.131.6.22
    JMXTRANS_JMX_PORT: 8004
    SECONDS_BETWEEN_RUNS: 1
