elasticsearch:
  image: elasticsearch:5
  container_name: elasticsearch
  restart: unless-stopped
  environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - /srv/elasticsearch:/usr/share/elasticsearch/data
logstash:
  image: jmx/logstash:v1
  restart: unless-stopped 
  command: logstash -f /etc/logstash/conf.d/logstash.conf 
# command: logstash  --debug  -f /etc/logstash/conf.d/logstash.conf 
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/jmx:/etc/logstash/jmx
    - ./testlog/log:/host/var/log
  ports:
    - "5000:5000"
    - "5044:5044"
    - "5007:5007/udp"
    - "4712:4712"
    - "4713:4713"
    - "4715:4715"
  links:
    - elasticsearch
kibana:
  image: kibana:5
  restart: unless-stopped  
  ports:
    - "5601:5601"
  links:
    - elasticsearch
