version: '3'  
services: 
  influxdba:
    image: tutum/influxdb:0.9
#    ports:
#      - "8083:8083"
#      - "8086:8086"
#      - "8089:8089/udp"
#      - "2003:2003"
    environment:
      - 'PRE_CREATE_DB=sensu'
      - 'UDP_DB=sensu'
      - 'UDP_PORT=8089'
      - 'COLLECTD_DB=collectd'
      - 'GRAPHITE_DB=jvm'
      - 'FORCE_HOSTNAME=influxdba:8088'
    volumes:
      - /srv/influxdb:/data
    networks:
      - influxnet
    deploy:
#      mode: global
      restart_policy:
        condition: any
#      placement:
#        constraints:
#          - node.role == manager 
  influxdb:
    image: tutum/influxdb:0.9
 #   ports:
 #     - "8083:8083"
 #     - "8086:8086"
 #     - "8089:8089/udp"
 #     - "2003:2003"
    environment:
      - 'PRE_CREATE_DB=sensu'
      - 'UDP_DB=sensu'
      - 'UDP_PORT=8089'
      - 'COLLECTD_DB=collectd'
      - 'GRAPHITE_DB=jvm'
      - 'FORCE_HOSTNAME=influxdb:8089'
      - 'JOIN=influxdba:8088'
    volumes:
      - /srv/influxdb:/data
    networks:
      - influxnet
    links:
      - influxdba
    deploy:
#      mode: global
      restart_policy:
        condition: any
#      placement:
#        constraints:
#          - node.role == manager
networks:
  influxnet:
