version: '3'  
services: 
  influxdba:
    image: influxdb:cluster 
#    ports:
#      - "8083:8083"
#      - "8086:8086"
#      - "8089:8089/udp"
#      - "2003:2003"
    environment:
      - 'FORCE_HOSTNAME=influxdba'
      - 'PRE_CREATE_DB=sensu'
      - 'UDP_DB=sensu'
      - 'UDP_PORT=8089'
      - 'COLLECTD_DB=collectd'
      - 'GRAPHITE_DB=jvm'
#    volumes:
#      - /srv/influxdb:/data
    volumes:
      - /home/ubuntu/influx:/data
    networks:
      influxnet:
        aliases:
          - influxdb
    deploy:
#      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager 
  influxdb:
    image: influxdb:cluster
 #   ports:
 #     - "8083:8083"
 #     - "8086:8086"
 #     - "8089:8089/udp"
 #     - "2003:2003"
    environment:
      - 'FORCE_HOSTNAME=auto'
      - 'JOIN=influxdba:8088'
#    volumes:
#      - /srv/influx:/data
    volumes:
      - /home/ubuntu/influx:/data
    networks:
      - influxnet
    depends_on:
      - influxdba
    deploy:
#      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker 
networks:
  influxnet:
