version: "3"
services:

  elasticsearch:
    image: agoryachev/docker-swarm-elasticsearch:5.4.0
    ports:
      - "9200:9200"
    networks:
      - elastic_cluster
    environment:
      - SERVICE_NAME=elasticsearch
    volumes:
      - /home/ubuntu/data/elasticsearch:/usr/share/elasticsearch/data
    deploy:
      mode: global
      restart_policy:
        condition: any
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    ports:
      - "5601:5601"
    networks:
      - elastic_cluster
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
networks:
    elastic_cluster:
        external: true
